### ISSUE TITLE
Fails to build: possible openvdb error

### ISSUE THREAD

**Issue by asluizh** [rocm-arch/blender-rocm#2]
Fails with the following error:
```
lib/libextern_mantaflow.a(iovdb.cpp.o):iovdb.cpp:function openvdb::v9_1::points::TypedAttributeArray<float, openvdb::v9_1::points::TruncateCodec>::copy() const: error: undefined reference to 'openvdb::v9_1::points::AttributeArray::AttributeArray(openvdb::v9_1::points::AttributeArray const&, tbb::spin_mutex::scoped_lock const&)'
lib/libextern_mantaflow.a(iovdb.cpp.o):iovdb.cpp:function openvdb::v9_1::points::TypedAttributeArray<int, openvdb::v9_1::points::TruncateCodec>::copy() const: error: undefined reference to 'openvdb::v9_1::points::AttributeArray::AttributeArray(openvdb::v9_1::points::AttributeArray const&, tbb::spin_mutex::scoped_lock const&)'
```
Possible relation to this? https://devtalk.blender.org/t/compilation-fails-on-arch-with-openvdb/6225

I have experienced a similar issue compiling blender from their git before, and it builds successfully if I disable openvdb.
The openvdb package I have installed is the following: community/openvdb 9.1.0-1

**Comment by acxz** [comment]
If you find how to fix the error, feel free to send a PR!

**Comment by acxz** [comment]
I am not able to reproduce this error. @asluizh can you try building this package again with version `3.3.1-1`? Just comment here and I'll open the issue back up, if you still encounter the issue.
